server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audit_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: audit-service
      auto-offset-reset: earliest

  cloud:
    config:
      enabled: false

  logging:
    level:
      root: INFO
      org.springframework.web: INFO
      org.hibernate: INFO
      com.calvin: INFO

kafka:
  topic:
    audit: audit-events